# Written by Armin van der Togt
#  JANSSON_FOUND - System has JANSSON
#  JANSSON_INCLUDE_DIRS - The JANSSON include directories
#  JANSSON_LIBS - The libraries needed to use JANSSON


find_library(JANSSON_LIBS NAMES jansson PATHS ${JANSSON_DIR} PATH_SUFFIXES "bin")

find_path(JANSSON_INCLUDE_DIRS "jansson.h" PATHS ${JANSSON_DIR})

if (JANSSON_LIBS AND JANSSON_INCLUDE_DIRS)
	SET(JANSSON_FOUND 1)
else  (JANSSON_LIBS AND JANSSON_INCLUDE_DIRS)
	SET(JANSSON_FOUND 0)
endif  (JANSSON_LIBS AND JANSSON_INCLUDE_DIRS)

